In [ ]:
import pandas as pd

In [ ]:
df = pd.read_json('train.json') 
df

,tokens,labels,sentence
0,"[Snowflake, closed, a, $30M, Series-A, funding...","[1, 0, 0, 2, 3, 0, 0, 0, 5]",Snowflake closed a $30M Series-A funding round...
1,"[In, July-2024, HashiCorp, announced, a, $1.5B...","[0, 5, 1, 0, 0, 2, 3, 0, 0, 4]",In July-2024 HashiCorp announced a $1.5B Serie...
2,"[Insight-Partners, and, Tiger-Global, co-led, ...","[4, 0, 4, 0, 1, 0, 2, 3, 0, 5]",Insight-Partners and Tiger-Global co-led Datab...
3,"[OpenAI, raised, $15M, in, a, Series-B, round,...","[1, 0, 2, 0, 0, 3, 0, 0, 0, 4, 0, 5]",OpenAI raised $15M in a Series-B round led by ...
4,"[In, Q4-2024, Nubank, announced, a, $1.5B, Ser...","[0, 5, 1, 0, 0, 2, 3, 0, 0, 4]",In Q4-2024 Nubank announced a $1.5B Series-A r...
...,...,...,...
795,"[In, a, Growth, round, Figma, raised, $300M, w...","[0, 0, 3, 0, 1, 0, 2, 0, 4, 0]",In a Growth round Figma raised $300M with Khos...
796,"[In, a, Series-F, round, Monzo, raised, $1B, w...","[0, 0, 3, 0, 1, 0, 2, 0, 4, 0]",In a Series-F round Monzo raised $1B with Fore...
797,"[Scale-AI, raised, $250M, in, a, Pre-Seed, rou...","[1, 0, 2, 0, 0, 3, 0, 0, 0, 4, 0, 5]",Scale-AI raised $250M in a Pre-Seed round led ...
798,"[Spark-Capital, led, a, $250M, Series-C, inves...","[4, 0, 0, 2, 3, 0, 0, 1, 0, 5]",Spark-Capital led a $250M Series-C investment ...
799,"[Coinbase, raised, $100M, in, a, Series-F, rou...","[1, 0, 2, 0, 0, 3, 0, 0, 0, 4, 0, 5]",Coinbase raised $100M in a Series-F round led ...

In [10]:
df.columns

Index(['tokens', 'labels', 'sentence'], dtype='object')

In [11]:
type(df.iloc[0]['tokens'])

list

In [16]:
df = df.loc[:,['labels','sentence']]
df

,labels,sentence
0,"[1, 0, 0, 2, 3, 0, 0, 0, 5]",Snowflake closed a $30M Series-A funding round...
1,"[0, 5, 1, 0, 0, 2, 3, 0, 0, 4]",In July-2024 HashiCorp announced a $1.5B Serie...
2,"[4, 0, 4, 0, 1, 0, 2, 3, 0, 5]",Insight-Partners and Tiger-Global co-led Datab...
3,"[1, 0, 2, 0, 0, 3, 0, 0, 0, 4, 0, 5]",OpenAI raised $15M in a Series-B round led by ...
4,"[0, 5, 1, 0, 0, 2, 3, 0, 0, 4]",In Q4-2024 Nubank announced a $1.5B Series-A r...
...,...,...
795,"[0, 0, 3, 0, 1, 0, 2, 0, 4, 0]",In a Growth round Figma raised $300M with Khos...
796,"[0, 0, 3, 0, 1, 0, 2, 0, 4, 0]",In a Series-F round Monzo raised $1B with Fore...
797,"[1, 0, 2, 0, 0, 3, 0, 0, 0, 4, 0, 5]",Scale-AI raised $250M in a Pre-Seed round led ...
798,"[4, 0, 0, 2, 3, 0, 0, 1, 0, 5]",Spark-Capital led a $250M Series-C investment ...
799,"[1, 0, 2, 0, 0, 3, 0, 0, 0, 4, 0, 5]",Coinbase raised $100M in a Series-F round led ...

In [ ]:
df.to_json('train_edited.json', orient='records')